## Pointer based registration
pointer:
  tooltip name: drill_tip # Rigid body that is attached to the tip of the tool
  number of points: 5
  name of points:
    - F1
    - F2
    - F3
    - F4
    - F5

  object name: TB04_anatomical_origin


## Optical Tracker Registration
optical tracker:
  namespace: /atracsys #rostopic name for the optical marker
  name of points:
    - anatomy

## Hand-Eye Regisration
hand eye:
  # Both the robot and the marker status should be published using CRTK
  namespace: /REMS/Research/ #namespace for the robot 
  marker name: atracsys/Endoscope # This name should used for both rostopic name and object name in AMBF
  joint name: Tilt Distal Linkage and Force Sensor
  optical tracker name: Tracker
  resolution: 0.001
  number of points: 1000
  registered HE result:
    q_rot: {x: -0.41203665, y: 0.57009639,  z: 0.55851358, w: 0.43963449}
    q_dual: {x: -0.03224828, y: -0.06383405, z: 0.02621267, w: 0.01925225}



# ## Pivot calibration
pivot:
  tooltip name: drill_tip
  namespace: /REMS/Research/ #namespace for the robot 
  marker name: atracsys/Endoscope
  resolution: 0.01
  number of points: 150
  # registered pivot result:
    # Orignal Point
    # t_tip: 
    #   x: -0.077053
    #   y:  0.150933
    #   z:  0.043711

    # t_tip:
    #   x: 0.0738
    #   z: -0.1486
    #   y: -0.0451

    # 0827
    # t_tip: 
    #   x: -0.07555049605 
    #   y: 0.14830072358  
    #   z: 0.04693415223

    # 0827 Dual
    # t_tip:
    #   x: 0.113366
    #   y: -0.161801
    #   z: 0.084349

    #0828
    # t_tip:
    #   x: 0.11388708842    
    #   y: -0.15785066246
    #   z: 0.08484844486

    # 0909
    # t_tip:
    #   x: 0.112303
    #   y: -0.161753
    #   z:  0.084276

    # 0910 Optical Tracker
    # t_tip:
    #   x: 0.112229
    #   y: -0.161895
    #   z:  0.084108

    # 0910 Rotbot Pivot Calibration
    # t_tip: 
    #   x: 0.070891 
    #   y: -0.061150
    #   z: -0.125319 
    
    # 1011 Rotbot Pivot Calibration
    # t_tip: {x: -0.104696, y: 0.142219, z: 0.030938} # 2mm

    # 1012 Pivot calibration
    # t_tip: {x: -0.094091, y: 0.129397, z: 0.024572} # 3mm

    # t_tip: {x: -0.088593, y: 0.131075, z: 0.026452} # 4mm

    # t_tip: {x: -0.092852, y: 0.131702, z: 0.025021} # 6mm

