## Pointer based registration
pointer:
  tooltip name: drill_tip # Rigid body that is attached to the tip of the tool
  number of points: 20
  name of points:
    - Sphere_00
    - Sphere_01
    - Sphere_02
    - Sphere_03
    - Sphere_04
    - Sphere_05
    - Sphere_06
    - Sphere_07
    - Sphere_08
    - Sphere_08
    - Sphere_09
    - Sphere_10
    - Sphere_11
    - Sphere_12
    - Sphere_13
    - Sphere_14
    - Sphere_15
    - Sphere_16
    - Sphere_17
    - Sphere_18
    - Sphere_19
  object name: Registration Cube

## Optical Tracker Registration
optical tracker:
  namespace: /atracsys #rostopic name for the optical marker
  name of points:
    - anatomy

## Hand-Eye Regisration
hand eye:
  # Both the robot and the marker status should be published using CRTK
  namespace: /REMS/Research/ #namespace for the robot 
  marker name: atracsys/Anspoch_drill # This name should used for both rostopic name and object name in AMBF
  joint name: dovetail_male
  optical tracker name: Tracker
  resolution: 0.001
  number of points: 500
  registered HE result:
    # 0811
    # q_rot: 
    #   x: -0.44392565
    #   y: -0.43748763
    #   z: 0.57720114
    #   w: 0.52761105
    # q_dual: 
    #   x: 0.05157883    
    #   y: -0.03933842
    #   z: -0.02773238
    #   w: 0.04111789
    
    # # 0824
    # q_rot: 
    #   x: 0.28250703     
    #   y: -0.34652492
    #   z: 0.88047073
    #   w: 0.1577389
    # q_dual: 
    #   x: 0.04093878     
    #   y: -0.03396216
    #   z: -0.02833392
    #   w: 0.01022549

    # 0824
    # q_rot: 
    #   x: 0.31249885      
    #   y: -0.31309434
    #   z: 0.8859285
    #   w: 0.13945287
    # q_dual: 
    #   x: 0.04779426    
    #   y: -0.01977394
    #   z: -0.02610652
    #   w: 0.0143543

    #0826
    # q_rot: 
    #   x: 0.31819239     
    #   y: -0.31104621
    #   z: 0.87892694
    #   w: 0.1717303
    # q_dual: 
    #   x: 0.03030915    
    #   y: -0.02936303
    #   z: -0.02448269
    #   w: 0.01596162
    q_rot:
      x: -0.7758928  
      y: -0.2857084   
      z: 0.03552252  
      w: 0.56133699
    q_dual:
      x: 0.02420084    
      y: -0.02888176
      z: -0.00910537
      w: 0.01932698


# ## Pivot calibration
pivot:
  tooltip name: drill_tip
  namespace: /REMS/Research/ #namespace for the robot 
  marker name: atracsys/Anspoch_drill
  resolution: 0.0001
  number of points: 600
  registered pivot result:
    # Orignal Point
    # t_tip: 
    #   x: -0.077053
    #   y:  0.150933
    #   z:  0.043711

    # t_tip:
    #   x: 0.0738
    #   z: -0.1486
    #   y: -0.0451

    # Testing
    # t_tip: 
    #   x:  0.077053
    #   z:  -0.150933
    #   y:  -0.043711

    # 0827
    t_tip: 
      x: 0.07555049605 
      z: -0.14830072358  
      y: -0.04693415223

