## Pointer based registration
pointer:
  tooltip name: "drill_tip" # Rigid body that is attached to the tip of the tool
  number of points: 8
  name of points:
    - Sphere_01
    - Sphere_02
    - Sphere_03
    - Sphere_04
    - Sphere_05
    - Sphere_06
    - Sphere_07
    - Sphere_08

## Optical Tracker Registration
optical tracker:
  namespace: "/adapter" #rostopic name for the optical marker
  name of points:
    - marker_body